/**
 * Branch Manager
 * Creates design/* branches in GitHub and opens PRs from batch flush payloads.
 */

import type { BatchFlushPayload, PendingChange, Project } from "@uxbridge/types";

import { createDesignBranch } from "../github/branch-ops.js";
import { createPR } from "../github/pr-manager.js";

/** Format branch name: design/button-input-badge-2026-04-08 */
export function formatBranchName(
  prefix: string,
  changes: PendingChange[],
  date = new Date(),
): string {
  const dateStr = date.toISOString().slice(0, 10); // YYYY-MM-DD
  const nodeNames = [...new Set(changes.map((c) => c.nodeName))]
    .slice(0, 3)
    .map((n) => n.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))
    .join("-");
  return `${prefix}${nodeNames}-${dateStr}`;
}

/** Build the PR description body */
function buildPRBody(
  changes: PendingChange[],
  figmaFileKey: string,
  projectFigmaUrl?: string,
): string {
  const lines: string[] = [
    "## Design changes from Figma",
    "",
    "| Component | Properties | Significance |",
    "|-----------|------------|--------------|",
    ...changes.map(
      (c) => `| ${c.nodeName} | ${c.changedProperties.slice(0, 5).join(", ")} | ${c.significance} |`,
    ),
    "",
    `**Batch size:** ${changes.length} changes`,
    "",
  ];

  if (projectFigmaUrl) {
    lines.push(`**Figma file:** [Open in Figma](${projectFigmaUrl})`);
  }

  lines.push("", "_Generated by UxBridge Sync_");
  return lines.join("\n");
}

export async function createDesignPR(
  payload: BatchFlushPayload,
  project: Project,
  files: Array<{ path: string; content: string }>,
): Promise<{ prNumber: number; prUrl: string; branchName: string; sha: string }> {
  const branchName = formatBranchName(
    project.design_branch_prefix,
    payload.changes,
  );

  const significantChanges = payload.changes.filter(
    (c) => c.significance === "HIGH" || c.significance === "MEDIUM",
  );

  const prTitle = `[design] ${significantChanges
    .slice(0, 3)
    .map((c) => c.nodeName)
    .join(", ")} — batch sync`;

  const prBody = buildPRBody(
    payload.changes,
    payload.figmaFileKey,
  );

  const { sha } = await createDesignBranch({
    repo: project.github_repo,
    baseBranch: project.pr_target_branch,
    branchName,
    commitMessage: `[design] Batch sync: ${payload.changes.length} changes via UxBridge`,
    files,
    prTitle: "",
    prBody: "",
  });

  const pr = await createPR({
    repo: project.github_repo,
    head: branchName,
    base: project.pr_target_branch,
    title: prTitle,
    body: prBody,
    draft: false,
  });

  return {
    prNumber: pr.number,
    prUrl: pr.url,
    branchName,
    sha,
  };
}
